print('\033[5;31;40m')
print("="*70)
print("QQQQQQ Q    Q   QQ    Q    Q QQQQQQ QQQQQQ Q Q    Q   QQ   QQQQQQ")
print("    Q  Q    Q  Q  Q   QQ   Q Q    Q     Q  Q Q    Q  Q  Q  Q    Q")
print("   Q   Q    Q Q    Q  Q Q  Q Q         Q   Q Q    Q Q    Q Q    Q")
print("  Q    QQQQQQ QQQQQQ  Q  Q Q Q        Q    Q QQQQQQ QQQQQQ Q    Q")
print(" Q     Q    Q Q    Q  Q   QQ Q   QQ  Q     Q Q    Q Q    Q Q    Q")
print("QQQQQQ Q    Q Q    Q  Q    Q QQQQQQ QQQQQQ Q Q    Q Q    Q QQQQQQ")
print("="*70)
